CREATE TABLE public.pessoa (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	cpf text,
	cnpj text,
	nome character varying(250) NOT NULL,
	fone character(11),
	email character varying(250),
	CONSTRAINT cliente_pk PRIMARY KEY (id),
	CONSTRAINT cpf_ix UNIQUE (cpf),
	CONSTRAINT cnpj_ix UNIQUE (cnpj),
	CONSTRAINT chk_null_cpfcnpj CHECK ((NOT((cpf,cnpj) IS NULL)))
);
-- ddl-end --
ALTER TABLE public.pessoa OWNER TO root;
-- ddl-end --